name: Build, Test, and Report

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # Replace with your .NET version

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Tests with Report
        run: |
          dotnet test --no-build --configuration Release --logger "trx"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/*.trx -targetdir:TestResults -reporttypes:"HtmlInline;TextSummary"
          cat TestResults/Summary.txt

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults/

      - name: Send email notification with Test Summary
        if: always() # Ensures email is sent regardless of previous step success/failure
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub Actions Build/Test Result
          body: The build and test process completed. Check the attached report for details.
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: TestResults/Summary.txt
