name: Build, Test, and Report Detailed

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # Replace with your .NET version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test and Capture Results
        run: |
          dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" > test_results.txt

      - name: Process Test Results
        id: process_test_results
        run: |
          # Extracting test results - simple example
          passed_tests=$(grep -oP 'Passed!  \K.*' test_results.txt)
          failed_tests=$(grep -oP 'Failed!  \K.*' test_results.txt)
          echo "Passed Tests: $passed_tests"
          echo "Failed Tests: $failed_tests"
          echo "::set-output name=passed_tests::$passed_tests"
          echo "::set-output name=failed_tests::$failed_tests"

      - name: Send email notification with Test Details
        if: always() # Ensures email is sent regardless of previous step success/failure
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub Actions Detailed Test Result
          body: |
            Passed Tests:
            ${{ steps.process_test_results.outputs.passed_tests }}
            
            Failed Tests:
            ${{ steps.process_test_results.outputs.failed_tests }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.SMTP_USERNAME }}
