name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.7' # Modify with your .NET version

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release
